# Generated by Django 5.1.3 on 2024-11-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_contribuyente',
            name='id',
            field=models.AutoField(db_column='Id_TCont', primary_key=True, serialize=False),
        ),
    ]
