# Generated by Django 5.1.3 on 2024-11-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_trabajador_documento_trabajador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento_cliente',
            field=models.CharField(max_length=20),
        ),
    ]
